# This is a basic workflow to help you get started with Actions

name: Create Extract

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
        
defaults:
  run:
    shell: powershell
    working-directory: extract

jobs:                
  extract:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: paulhatch/semantic-version@v3
        id: semanticVersion
        with:
          # The branch to count commits on
          branch: "master"
              # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "extract"
        
      - name: Calculate tag version
        id: calculateTagVersion
        run: |
          $tag = "${{ steps.semanticVersion.outputs.version }}.$($env:GITHUB_RUN_ID%65536)"
          echo "::set-output name=tag::$tag"
    
      - name: Restore Extract NuGets
        run: nuget restore
        
      - name: Add MSBuild to the path
        uses: microsoft/setup-msbuild@v1.0.1
        
      - name: Compile Extract in Release configuration
        run: msbuild extract.sln /property:Configuration=Release
        
      - name: Create Release
        id: create-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.calculateTagVersion.outputs.tag }}
          release_name: Extract Release ${{ steps.calculateTagVersion.outputs.tag }}
          body: |
            Automated Build of Extract
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}  
          asset_path: ./extract/x64/Release/Extract.exe
          asset_name: extract.exe
          asset_content_type: application/vnd.microsoft.portable-executable
